export const FETCH_COUNTRY_RESULT = 'country/FETCH_RESULT';
export const FETCH_COUNTRY_RESULT_SUCCESS = 'country/FETCH_RESULT_SUCCESS';
export const FETCH_COUNTRY_RESULT_FAILURE = 'country/FETCH_RESULT_FAILURE';

export const CLEAR_COUNTRY_CHOICES = 'country/CLEAR_CHOICES';
